; MMH NSIS customization.
;
; Business logic (unchanged from the original):
;   1. Default install directory: D:\MMH when the D: drive exists, otherwise
;      Program Files (x64). Written into the registry key electron-builder reads
;      during .onInit to override the default INSTALL_ROOT.
;   2. Uninstall keeps user data: the app stores its database under
;      $INSTDIR\data. electron-builder removes $INSTDIR recursively, so we move
;      data aside before that and restore it afterwards.
;
; Visual customization (2026-10-07): the welcome / finish pages are replaced
; with custom nsDialogs pages that draw a full-bleed dark brand background
; (installerWelcome.bmp / uninstallerWelcome.bmp, generated by
; scripts/generate-nsis-bitmaps.cjs) with light headline copy, instead of the
; stock grey-and-white MUI2 pages. This modernises the wizard without touching
; electron-builder's auto-update (NsisUpdater) or install/uninstall logic.
;
; The custom page structure mirrors electron-builder's own multiUserUi.nsh
; (PAGE_INSTALL_MODE): page content is built inside the Pre callback
; (nsDialogs::Create -> controls -> nsDialogs::Show), then wired via
; PageEx custom / UninstPage custom.

; nsDialogs is already included by MUI2; include again only so the ${NSD_*}
; macros resolve regardless of include order (redefining macros is harmless).
!include "nsDialogs.nsh"

; Shared handles. Declared once at top level so both the install and uninstall
; custom pages can use them without re-declaring (a duplicate Var is fatal).
Var mmhBgImage
Var mmhBgBitmap
Var mmhTitleFont

; Unpack + load the full-bleed background bitmap for a custom page.
!macro MMH_PAGE_BACKGROUND bmpName
  ${NSD_CreateBitmap} 0 0 100% 100% ""
  Pop $mmhBgImage
  ${NSD_SetStretchedImage} $mmhBgImage "$PLUGINSDIR\${bmpName}" $mmhBgBitmap
!macroend

; Create a light (white) label over the dark background, optionally bold.
!macro MMH_TITLE outVar x y w h text size
  ${NSD_CreateLabel} ${x}u ${y}u ${w}u ${h}u "${text}"
  Pop ${outVar}
  SetCtlColors ${outVar} 0xFFFFFF transparent
  CreateFont $mmhTitleFont "$(^Font)" "${size}" "700"
  SendMessage ${outVar} ${WM_SETFONT} $mmhTitleFont 0
!macroend

!macro MMH_TEXT outVar x y w h text
  ${NSD_CreateLabel} ${x}u ${y}u ${w}u ${h}u "${text}"
  Pop ${outVar}
  SetCtlColors ${outVar} 0xFFFFFF transparent
!macroend

; ------------------------------------------------------------------ Welcome

!macro customWelcomePage

  Var /GLOBAL mmhWelcomePage

  !insertmacro MUI_PAGE_INIT

  Function mmh.WelcomePre
    InitPluginsDir
    File /oname=$PLUGINSDIR\welcome.bmp "${BUILD_RESOURCES_DIR}\installerWelcome.bmp"

    nsDialogs::Create 1044
    Pop $mmhWelcomePage
    nsDialogs::SetRTL $(^RTL)

    !insertmacro MMH_PAGE_BACKGROUND welcome.bmp

    !insertmacro MMH_TITLE $0 300 22 700 40 "MMH 家庭财务工作台" 16
    !insertmacro MMH_TEXT $1 300 74 700 20 "本地优先的家庭记账与全资产管理"
    !insertmacro MMH_TEXT $2 300 100 700 60 "数据保存在你自己的设备上，支持多账本、多成员、账户流水、投资、存款、房产、统计报表与 AI 助手。$\r$\n点击「下一步」开始安装。"

    nsDialogs::Show
  FunctionEnd

  Function mmh.WelcomeLeave
  FunctionEnd

  PageEx custom
    PageCallbacks mmh.WelcomePre mmh.WelcomeLeave
  PageExEnd

!macroend

; ------------------------------------------------------------------ Finish

!macro customFinishPage

  Var /GLOBAL mmhFinishPage
  Var /GLOBAL mmhFinishLaunch
  Var /GLOBAL mmhLaunchArgs

  !insertmacro MUI_PAGE_INIT

  Function mmh.FinishPre
    InitPluginsDir
    File /oname=$PLUGINSDIR\welcome.bmp "${BUILD_RESOURCES_DIR}\installerWelcome.bmp"

    nsDialogs::Create 1044
    Pop $mmhFinishPage
    nsDialogs::SetRTL $(^RTL)

    !insertmacro MMH_PAGE_BACKGROUND welcome.bmp

    !insertmacro MMH_TITLE $0 300 22 700 40 "安装完成" 16
    !insertmacro MMH_TEXT $1 300 74 700 40 "MMH 已安装到你的设备，记账数据保存在本地。"

    ${NSD_CreateCheckbox} 300u 128u 700u 16u "立即启动 MMH"
    Pop $mmhFinishLaunch
    SetCtlColors $mmhFinishLaunch 0xFFFFFF transparent
    ${NSD_Check} $mmhFinishLaunch

    nsDialogs::Show
  FunctionEnd

  Function mmh.FinishLeave
    ${NSD_GetState} $mmhFinishLaunch $0
    ${if} $0 == ${BST_CHECKED}
      ; Launch the app. Inlined (rather than reusing the StartApp macro) so we
      ; don't depend on its `Var /GLOBAL startAppArgs` being declared exactly
      ; once; `$launchLink` and ${isUpdated} come from electron-builder.
      ${if} ${isUpdated}
        StrCpy $mmhLaunchArgs "--updated"
      ${else}
        StrCpy $mmhLaunchArgs ""
      ${endif}
      ${StdUtils.ExecShellAsUser} $0 "$launchLink" "open" "$mmhLaunchArgs"
    ${endif}
  FunctionEnd

  PageEx custom
    PageCallbacks mmh.FinishPre mmh.FinishLeave
  PageExEnd

!macroend

; ------------------------------------------------------------------ Uninstall welcome

!macro customUnWelcomePage

  Var /GLOBAL mmhUnWelcomePage

  !insertmacro MUI_UNPAGE_INIT

  Function un.mmh.UnWelcomePre
    InitPluginsDir
    File /oname=$PLUGINSDIR\welcome.bmp "${BUILD_RESOURCES_DIR}\uninstallerWelcome.bmp"

    nsDialogs::Create 1044
    Pop $mmhUnWelcomePage
    nsDialogs::SetRTL $(^RTL)

    !insertmacro MMH_PAGE_BACKGROUND welcome.bmp

    !insertmacro MMH_TITLE $0 300 22 700 40 "卸载 MMH" 16
    !insertmacro MMH_TEXT $1 300 74 700 40 "将从此设备移除 MMH。你的记账数据会保留在本地，重新安装后仍可继续使用。"

    nsDialogs::Show
  FunctionEnd

  Function un.mmh.UnWelcomeLeave
  FunctionEnd

  UninstPage custom un.mmh.UnWelcomePre un.mmh.UnWelcomeLeave

!macroend

; ------------------------------------------------------------------ Business logic (unchanged)

!macro preInit
  IfFileExists "D:\" 0 +3
  WriteRegExpandStr HKCU "${INSTALL_REGISTRY_KEY}" InstallLocation "D:\MMH"
  Goto +2
  WriteRegExpandStr HKCU "${INSTALL_REGISTRY_KEY}" InstallLocation "$PROGRAMFILES64\MMH"
!macroend

!macro customUnInstall
  IfFileExists "$INSTDIR\data\*.*" 0 +3
  Rename "$INSTDIR\data" "$TEMP\MMH-data-backup"
  Goto +1
!macroend

!macro customUnInstallSection
  Section "-MMH user data"
    IfFileExists "$TEMP\MMH-data-backup\*.*" 0 +3
    CreateDirectory "$INSTDIR"
    Rename "$TEMP\MMH-data-backup" "$INSTDIR\data"
    Goto +1
  SectionEnd
!macroend
