import { prisma } from "@/lib/db/prisma";
import { getHouseholdScope } from "@/lib/server/household-scope";
import { buildAccountDisplayOption, buildFlatAccountOptions, buildGroupedAccountOptions } from "@/lib/account-display";
import { buildCategorySmartSelectOptions } from "@/components/categorySmartSelect";
import { categoryOrderBy } from "@/lib/category-order";
import { decodeScheduledTaskMemo, getLoanScheduledPlanRole, isSystemManagedScheduledTask, normalizeScheduledTaskType, scheduledTaskTypeLabel } from "@/lib/scheduled-task";
import { ACTIVE_DEBT_EPSILON } from "@/lib/server/debt-view-data";
import { AccountKind, TransactionType } from "@prisma/client";
import { recalcAndSaveAccountBalance } from "@/lib/server/account-balance";
import { revalidateAfterTxChange } from "@/lib/server/revalidate";
import { toStatementMonth } from "@/lib/date-utils";
import { allocateBuyFailedRefunds, getConfirmedBuyAmount } from "@/lib/fund/refund-link";
import { getFundProfileNameMap, normalizeFundDisplayName } from "@/lib/fund/fundProfile";
import { RegularInvestClient } from "./RegularInvestClient";
import { MobileRegularInvest } from "@/components/mobile/MobileRegularInvest";
import { resolveCreditCardRepaymentCategory } from "@/lib/default-categories";
import { isCreditCardRepaymentTransfer, recordMatchesRegularInvestPlan } from "@/lib/transaction-semantics";
import { getServerAccountLabelFields } from "@/lib/server/account-label-fields";
import { getServerT } from "@/lib/server/i18n";
import { createTransaction } from "@/lib/server/sidebar-actions/transaction-actions";
import { normalizeLoanRepaymentMethod } from "@/lib/loan-repayment";

async function updateScheduledTransferRecord(formData: FormData) {
  "use server";
  const { householdId } = await getHouseholdScope();

  const entryId = String(formData.get("entryId") ?? "").trim();
  const dateStr = String(formData.get("date") ?? "").trim();
  const amountRaw = Number(String(formData.get("amount") ?? "").trim());
  const fromAccountId = String(formData.get("fromAccountId") ?? "").trim();
  const toAccountId = String(formData.get("toAccountId") ?? "").trim();
  const note = String(formData.get("note") ?? "").trim();
  const toNote = String(formData.get("toNote") ?? "").trim();

  if (!entryId) return { ok: false as const, error: "Missing record ID" };
  if (!dateStr || Number.isNaN(new Date(dateStr).getTime())) return { ok: false as const, error: "Invalid date" };
  const amountAbs = Number.isFinite(amountRaw) ? Math.abs(amountRaw) : 0;
  if (amountAbs <= 0) return { ok: false as const, error: "Invalid amount" };
  if (!fromAccountId || !toAccountId) return { ok: false as const, error: "Transfer requires both from and to accounts" };
  if (fromAccountId === toAccountId) return { ok: false as const, error: "From and to accounts must differ" };

  try {
    const date = new Date(dateStr);
    const updated = await prisma.$transaction(async (tx) => {
      const entry = await tx.txRecord.findUnique({ where: { id: entryId } });
      if (!entry) throw new Error("Record not found");
      if (entry.householdId && entry.householdId !== householdId) throw new Error("Record does not belong to the current book");
      if (!entry.regularInvestPlanId || entry.source !== "scheduled_task") throw new Error("This is not a transfer record generated by a scheduled task");

      const [fromAcc, toAcc] = await Promise.all([
        tx.account.findUnique({ where: { id: fromAccountId } }),
        tx.account.findUnique({ where: { id: toAccountId } }),
      ]);
      if (!fromAcc || !toAcc) throw new Error("Account not found");
      if (fromAcc.householdId !== householdId || toAcc.householdId !== householdId) throw new Error("Account does not belong to the current book");

      const statementMonth =
        (toAcc.kind === AccountKind.bank_credit || toAcc.kind === AccountKind.loan) && toAcc.billingDay
          ? toStatementMonth(date, toAcc.billingDay, toAcc.billingDayTxPeriod)
          : null;
      const repaymentCategory = isCreditCardRepaymentTransfer({
        type: TransactionType.transfer,
        accountKind: fromAcc.kind,
        toAccountKind: toAcc.kind,
      })
        ? await resolveCreditCardRepaymentCategory(tx, householdId)
        : null;

      const updated = await tx.txRecord.update({
        where: { id: entryId },
        data: {
          type: TransactionType.transfer,
          date,
          amount: -amountAbs,
          accountId: fromAcc.id,
          accountName: fromAcc.name,
          toAccountId: toAcc.id,
          toAccountName: toAcc.name,
          categoryId: repaymentCategory?.id ?? null,
          categoryName: repaymentCategory?.name ?? null,
          statementMonth,
          note: note || null,
          toNote: (toNote || note) || null,
        },
        select: {
          accountId: true,
          toAccountId: true,
        },
      });
      return {
        oldAccountId: entry.accountId,
        oldToAccountId: entry.toAccountId,
        accountId: updated.accountId,
        toAccountId: updated.toAccountId,
      };
    });

    const accountsToRecalc = new Set([updated.oldAccountId, updated.oldToAccountId, updated.accountId, updated.toAccountId].filter(Boolean));
    await Promise.all([...accountsToRecalc].map((accountId) => recalcAndSaveAccountBalance(accountId!).catch(() => {})));
    revalidateAfterTxChange();
    return { ok: true as const };
  } catch (error) {
    return { ok: false as const, error: error instanceof Error ? error.message : "Save failed" };
  }
}

function recordMatchesTask(taskType: string, entry: { source: string | null }) {
  return recordMatchesRegularInvestPlan(taskType, entry);
}

export default async function RegularInvestPage() {
  const { hidFilter } = await getHouseholdScope();
  const t = await getServerT();
  const accountLabelFields = await getServerAccountLabelFields();

  const [plans, accounts, groups, institutions, insuranceProducts, categories] = await Promise.all([
    prisma.regularInvestPlan.findMany({
      where: hidFilter,
      orderBy: { nextRunDate: "asc" },
    }),
    prisma.account.findMany({
      where: { isPlaceholder: { not: true }, ...hidFilter },
      include: { Institution: true, AccountGroup: true },
      orderBy: [{ isActive: "desc" }, { name: "asc" }],
    }),
    prisma.accountGroup.findMany({
      where: hidFilter,
      orderBy: [{ sortOrder: "asc" }, { name: "asc" }],
    }),
    prisma.institution.findMany({
      where: hidFilter,
      orderBy: { name: "asc" },
    }),
    prisma.insuranceProduct.findMany({
      where: hidFilter,
      include: {
        Account: true,
        Institution: true,
        OwnerGroup: true,
      },
      orderBy: [{ status: "asc" }, { name: "asc" }],
    }),
    prisma.category.findMany({
      where: hidFilter,
      select: {
        id: true,
        name: true,
        type: true,
        parentId: true,
        sortOrder: true,
        isSystem: true,
      },
      orderBy: categoryOrderBy(),
    }),
  ]);

  const scheduledTaskByPlanId = new Map(plans.map((plan) => [plan.id, decodeScheduledTaskMemo(plan.memo)]));
  const planIds = plans.map((plan) => plan.id);
  const allEntries = planIds.length > 0
    ? await prisma.txRecord.findMany({
        where: {
          regularInvestPlanId: { in: planIds },
          deletedAt: null,
        },
        select: {
          id: true,
          date: true,
          createdAt: true,
          fundConfirmDate: true,
          fundArrivalDate: true,
          accountId: true,
          toAccountId: true,
          fundCode: true,
          fundSubtype: true,
          fundSourceEntryId: true,
          regularInvestPlanId: true,
          source: true,
          amount: true,
          fundUnits: true,
        },
      })
    : [];

  const { refundAmountByBuyId } = allocateBuyFailedRefunds(allEntries.map((entry) => ({
    id: entry.id,
    date: entry.date,
    createdAt: entry.createdAt,
    fundConfirmDate: entry.fundConfirmDate,
    fundArrivalDate: entry.fundArrivalDate,
    accountId: entry.accountId,
    toAccountId: entry.toAccountId,
    fundCode: entry.fundCode,
    fundSubtype: entry.fundSubtype,
    source: entry.source,
    amount: Number(entry.amount),
    fundSourceEntryId: entry.fundSourceEntryId,
  })));

  const statsByPlanId = new Map<string, { executedCount: number; executedAmount: number; confirmedCount: number; confirmedAmount: number }>();
  for (const entry of allEntries) {
    const planId = entry.regularInvestPlanId;
    if (!planId) continue;
    const task = scheduledTaskByPlanId.get(planId);
    if (!recordMatchesTask(task?.type ?? "fund_regular_invest", entry)) continue;
    if (!statsByPlanId.has(planId)) {
      statsByPlanId.set(planId, { executedCount: 0, executedAmount: 0, confirmedCount: 0, confirmedAmount: 0 });
    }
    const stats = statsByPlanId.get(planId)!;
    stats.executedCount++;
    stats.executedAmount += Math.abs(Number(entry.amount));
    if (entry.fundUnits != null && Number(entry.fundUnits) > 0) {
      stats.confirmedCount++;
      stats.confirmedAmount += getConfirmedBuyAmount(
        Number(entry.amount),
        refundAmountByBuyId.get(entry.id) ?? 0,
      );
    }
  }

  const accountOptions = accounts.map((account) => buildAccountDisplayOption(account, undefined, { fields: accountLabelFields }));
  const accountById = new Map(accountOptions.map((account) => [account.id, account]));
  // 贷款是否"仍关联着"与负债视图同口径：|余额| > ACTIVE_DEBT_EPSILON 才算在贷，
  // 已结清/空壳账户按"无关联贷款"处理（提示可放心删除）。
  const accountBalanceById = new Map(accounts.map((account) => [account.id, Number(account.balance ?? 0)]));
  const isLoanLinked = (accountId: string) => {
    const balance = accountBalanceById.get(accountId);
    return balance != null && Math.abs(balance) > ACTIVE_DEBT_EPSILON;
  };
  // 系统计划（存款到期/取息、债券到期/付息）的关联真源：存单 = 计划 memo 的
  // depositSourceEntryId（或 depm_/depi_ 前缀），债券存单 = bondm_/bondi_ 的存单 id
  // （债券与存款同为存单粒度：一笔买入 = 一张存单 = 一个持仓）。
  // 真源仍在 → 删除会一并删它；真源不存在/已软删 → 提示可放心删除。两侧口径一致。
  // 注意：存款存单「已取回」不算失效 —— buy 行仍在账户里就是有关联记录（09-17 修正）；
  // 债券存单按本金判据（本金归零 = 已了结，视为失效）。
  const systemPlanSourceByPlanId = new Map<string, { kind: "deposit" | "bond"; name: string; linked: boolean }>();
  const depositPlanLots = plans
    .filter((plan) => {
      const task = scheduledTaskByPlanId.get(plan.id);
      return task?.type === "deposit_maturity" || task?.type === "deposit_interest_payout";
    })
    .map((plan) => {
      const task = scheduledTaskByPlanId.get(plan.id)!;
      const lotId = task.depositSourceEntryId
        || (plan.id.startsWith("depm_") || plan.id.startsWith("depi_") ? plan.id.slice(5) : "");
      return { planId: plan.id, lotId };
    })
    .filter((item) => !!item.lotId);
  const bondPlanLots = plans
    .filter((plan) => {
      const task = scheduledTaskByPlanId.get(plan.id);
      return task?.type === "bond_maturity" || task?.type === "bond_interest_payout";
    })
    .map((plan) => ({
      planId: plan.id,
      lotId: plan.id.startsWith("bondm_") || plan.id.startsWith("bondi_") ? plan.id.slice(6) : "",
    }))
    .filter((item) => !!item.lotId);
  if (depositPlanLots.length > 0 || bondPlanLots.length > 0) {
    const [lots, bondLots, bondChildRows] = await Promise.all([
      depositPlanLots.length > 0
        ? prisma.txRecord.findMany({
            where: { id: { in: depositPlanLots.map((item) => item.lotId) }, deletedAt: null },
            select: { id: true, fundName: true },
          })
        : Promise.resolve([] as Array<{ id: string; fundName: string | null }>),
      bondPlanLots.length > 0
        ? prisma.bondTransaction.findMany({
            where: { id: { in: bondPlanLots.map((item) => item.lotId) }, deletedAt: null, ...hidFilter },
            select: { id: true, productName: true, grossAmount: true, BondProduct: { select: { name: true } } },
          })
        : Promise.resolve([] as Array<{
            id: string;
            productName: string | null;
            grossAmount: unknown;
            BondProduct: { name: string } | null;
          }>),
      // 债券存单的失效判据 = 本金是否归零：只统计指回该存单的赎回/核销子行。
      bondPlanLots.length > 0
        ? prisma.bondTransaction.groupBy({
            by: ["sourceBondTransactionId", "action"],
            where: {
              sourceBondTransactionId: { in: bondPlanLots.map((item) => item.lotId) },
              deletedAt: null,
              ...hidFilter,
            },
            _sum: { grossAmount: true },
          })
        : Promise.resolve([] as Array<{
            sourceBondTransactionId: string | null;
            action: string;
            _sum: { grossAmount: unknown };
          }>),
    ]);
    const liveLotById = new Map(lots.map((lot) => [lot.id, lot]));
    for (const item of depositPlanLots) {
      const lot = liveLotById.get(item.lotId);
      systemPlanSourceByPlanId.set(item.planId, {
        kind: "deposit",
        name: lot?.fundName ?? "存款",
        // 存单 buy 行仍在（未软删）= 有关联记录；已取回不影响判定。
        linked: !!lot,
      });
    }
    const clearedByLotId = new Map<string, number>();
    for (const row of bondChildRows) {
      if (!row.sourceBondTransactionId) continue;
      if (row.action !== "redeem" && row.action !== "switch_out" && row.action !== "write_off") continue;
      const amount = Math.abs(Number(row._sum.grossAmount ?? 0));
      clearedByLotId.set(row.sourceBondTransactionId, (clearedByLotId.get(row.sourceBondTransactionId) ?? 0) + amount);
    }
    const bondLotById = new Map(bondLots.map((lot) => [lot.id, lot]));
    for (const item of bondPlanLots) {
      const lot = bondLotById.get(item.lotId);
      const principal = lot
        ? Math.abs(Number(lot.grossAmount ?? 0)) - (clearedByLotId.get(item.lotId) ?? 0)
        : 0;
      systemPlanSourceByPlanId.set(item.planId, {
        kind: "bond",
        name: lot?.BondProduct?.name ?? lot?.productName ?? "债券",
        linked: !!lot && principal > ACTIVE_DEBT_EPSILON,
      });
    }
  }
  const profileFundNames = await getFundProfileNameMap(
    plans
      .filter((plan) => normalizeScheduledTaskType(plan.taskType ?? scheduledTaskByPlanId.get(plan.id)?.type) === "fund_regular_invest")
      .map((plan) => plan.fundCode),
  );

  const plansData = plans.map((plan) => {
    const stats = statsByPlanId.get(plan.id) ?? { executedCount: 0, executedAmount: 0, confirmedCount: 0, confirmedAmount: 0 };
    const fundAccount = accountById.get(plan.accountId);
    const cashAccount = plan.cashAccountId ? accountById.get(plan.cashAccountId) : null;
    const scheduledTask = scheduledTaskByPlanId.get(plan.id) ?? decodeScheduledTaskMemo(plan.memo);
    const taskType = normalizeScheduledTaskType(plan.taskType ?? scheduledTask.type);
    const profileFundName = taskType === "fund_regular_invest" ? profileFundNames.get(plan.fundCode) ?? null : null;
    const displayFundName = profileFundName ?? normalizeFundDisplayName(plan.fundCode, plan.fundName) ?? plan.fundName;
    const displayTargetName = taskType === "fund_regular_invest"
      ? profileFundName ?? normalizeFundDisplayName(plan.fundCode, plan.targetName) ?? displayFundName
      : plan.targetName;

    return {
      ...plan,
      planName: plan.planName ?? null,
      fundName: displayFundName,
      taskType,
      taskTypeLabel: scheduledTaskTypeLabel(taskType),
      taskTitle: displayTargetName ?? scheduledTask.title ?? null,
      targetName: displayTargetName ?? null,
      insuranceProductName: plan.insuranceProductName ?? null,
      taskFromAccountId: scheduledTask.fromAccountId ?? null,
      taskToAccountId: scheduledTask.toAccountId ?? null,
      taskCategoryId: scheduledTask.categoryId ?? null,
      taskCategoryName: scheduledTask.categoryName ?? null,
      taskInsuranceProductId: scheduledTask.insuranceProductId ?? null,
      taskNote: scheduledTask.note ?? null,
      taskAnnualRate: scheduledTask.annualRate ?? null,
      taskRepaymentMethod: scheduledTask.repaymentMethod ? normalizeLoanRepaymentMethod(scheduledTask.repaymentMethod) : null,
      taskRepaymentIntervalMonths: scheduledTask.repaymentIntervalMonths ?? null,
      taskLoanPlanRole: getLoanScheduledPlanRole(scheduledTask),
      isSystemTask: isSystemManagedScheduledTask(scheduledTask),
      taskLoanLinked: taskType === "loan_repayment" ? isLoanLinked(plan.accountId) : null,
      taskSystemSource: systemPlanSourceByPlanId.get(plan.id) ?? null,
      amount: Number(plan.amount),
      feeRate: plan.feeRate ? Number(plan.feeRate) : null,
      startDate: plan.startDate && Number.isFinite(plan.startDate.getTime()) ? plan.startDate.toISOString() : null,
      endDate: plan.endDate && Number.isFinite(plan.endDate.getTime()) ? plan.endDate.toISOString() : null,
      nextRunDate: plan.nextRunDate && Number.isFinite(plan.nextRunDate.getTime()) ? plan.nextRunDate.toISOString() : null,
      lastRunDate: plan.lastRunDate && Number.isFinite(plan.lastRunDate.getTime()) ? plan.lastRunDate.toISOString() : null,
      createdAt: plan.createdAt && Number.isFinite(plan.createdAt.getTime()) ? plan.createdAt.toISOString() : null,
      updatedAt: plan.updatedAt && Number.isFinite(plan.updatedAt.getTime()) ? plan.updatedAt.toISOString() : null,
      executedCount: stats.executedCount,
      executedAmount: stats.executedAmount,
      confirmedCount: stats.confirmedCount,
      confirmedAmount: stats.confirmedAmount,
      accountLabel: fundAccount?.label ?? plan.accountName,
      accountFullLabel: fundAccount?.fullLabel ?? plan.accountName,
      accountHoverTitle: fundAccount?.hoverTitle ?? null,
      accountGroupName: fundAccount?.groupName ?? "",
      cashAccountLabel: cashAccount?.label ?? plan.cashAccountName,
      cashAccountFullLabel: cashAccount?.fullLabel ?? plan.cashAccountName,
      cashAccountHoverTitle: cashAccount?.hoverTitle ?? null,
      cashAccountGroupName: cashAccount?.groupName ?? "",
    };
  });

  const investmentAccounts = accountOptions.filter((account) => account.kind === "investment" && account.investProductType === "fund");
  const cashAccounts = accountOptions.filter((account) => ["bank_debit", "ewallet", "cash"].includes(account.kind));
  const ordinaryAccounts = accountOptions.filter((account) => ["bank_debit", "bank_credit", "ewallet", "cash"].includes(account.kind));
  const loanAccounts = accountOptions.filter((account) => account.kind === "loan");
  const transferTargetAccounts = accountOptions.filter((account) => !account.id || !["insurance"].includes(account.kind));
  const incomeCategoryOptions = buildCategorySmartSelectOptions({
    categories,
    types: ["income"],
    typeLabels: { income: t("categoryType.income") },
    typeHeaderPrefix: "scheduled-income-category",
    includeTypeHeaders: false,
    t,
  });
  const expenseCategoryOptions = buildCategorySmartSelectOptions({
    categories,
    types: ["expense"],
    typeLabels: { expense: t("stats.expenseCategories") },
    typeHeaderPrefix: "scheduled-expense-category",
    includeTypeHeaders: false,
    t,
  });
  const expenseCategories = categories
    .filter((c) => c.type === "expense")
    .map((c) => ({ id: c.id, label: c.name, parentId: c.parentId, type: c.type, sortOrder: c.sortOrder, isSystem: c.isSystem }));
  const incomeCategories = categories
    .filter((c) => c.type === "income")
    .map((c) => ({ id: c.id, label: c.name, parentId: c.parentId, type: c.type, sortOrder: c.sortOrder, isSystem: c.isSystem }));
  const advanceCategories = categories
    .filter((c) => c.type === "advance")
    .map((c) => ({ id: c.id, label: c.name, parentId: c.parentId, type: c.type, sortOrder: c.sortOrder, isSystem: c.isSystem }));
  const insuranceProductOptions = insuranceProducts.map((product) => ({
    id: product.id,
    label: product.name,
    accountId: product.accountId,
    accountLabel: accountById.get(product.accountId)?.label ?? product.Account?.name ?? "",
    ownerGroupId: product.ownerGroupId ?? null,
    ownerGroupName: product.OwnerGroup?.name ?? null,
    premiumAmount: product.premiumAmount == null ? null : Number(product.premiumAmount),
    premiumFrequencyMonths: product.premiumFrequencyMonths == null ? null : Number(product.premiumFrequencyMonths),
    subLabel: [
      product.Institution?.shortName || product.Institution?.name,
      product.OwnerGroup?.name,
    ].filter(Boolean).join(" · "),
  }));

  return (
    <>
      <div className="h-full md:hidden">
        <MobileRegularInvest plans={plansData} />
      </div>
      <div className="hidden h-full md:block">
        <RegularInvestClient
      initialPlans={plansData}
      investmentAccounts={investmentAccounts}
      cashAccounts={cashAccounts}
      loanAccounts={loanAccounts}
      transferTargetAccounts={transferTargetAccounts}
      ordinaryAccounts={ordinaryAccounts}
      insuranceProductOptions={insuranceProductOptions}
      investmentAccountSSOptions={buildFlatAccountOptions(investmentAccounts)}
      cashAccountSSOptions={buildGroupedAccountOptions(cashAccounts)}
      transferTargetAccountSSOptions={buildGroupedAccountOptions(transferTargetAccounts)}
      ordinaryAccountSSOptions={buildGroupedAccountOptions(ordinaryAccounts)}
      incomeCategoryOptions={incomeCategoryOptions}
      expenseCategoryOptions={expenseCategoryOptions}
      expenseCategories={expenseCategories}
      incomeCategories={incomeCategories}
      advanceCategories={advanceCategories}
      allAccountSSOptions={buildGroupedAccountOptions(accountOptions)}
      nestedFieldData={{
        groupId: groups.map((group) => ({ id: group.id, name: group.name })),
        institutionId: institutions.map((institution) => ({ id: institution.id, name: institution.name, type: institution.type ?? undefined })),
      }}
      transactionCreateAction={createTransaction}
          transactionEditAction={updateScheduledTransferRecord}
        />
      </div>
    </>
  );
}
